### ISSUE TITLE
the script doesn't work.

### ISSUE THREAD

**Issue by lmssieh** [iBLiSSIN/Surviv.io-Gun-Reskin#1]
also from where did you get the skins, they look great in-game.

**Comment by iBLiSSIN** [comment]
try to disable other script XD

**Comment by iBLiSSIN** [comment]
also I'm updated it

**Comment by lmssieh** [comment]
@iBLiSSIN you should rename the images to match the key52code

```js
else if(key52.match(/scout_elite/g)) {
        tracerColors[key52].worldImg.sprite = "https://raw.githubusercontent.com/iBLiSSIN/Surviv.io-Gun-Reskin/main/guns-skin/scout.png";
        tracerColors[key52].worldImg.tint = 0xFFFFFF
    }
````

for example you should rename scout.png to scout_elite.png, this will help reduce the code a lot.

**Comment by iBLiSSIN** [comment]
can you folk it then edit ?
I'm so busy now :(

**Comment by lmssieh** [comment]
sure thing.
